lib: skip Journal in redfish enumerate
Symptom:
"Verify Redfish Unresponsive URL paths" test item got failed.
ValueError: The HTTP status code was not valid:
status:                                           400
valid_status_codes:
  [0]:                                            200
  [1]:                                            404
  [2]:                                            405
  [3]:                                            500

Root cause:
When doing Redfish Enumerate Request into /redfish/v1/Managers/bmc/LogServices/Journal,
something the response status code return 400 that is not in valid_status_codes list.
And due to Journal log entries seems will be overwrited accroding
LogService.json schema "OverWritePolicy": "WrapsWhenFull".
Thus, Enumerate Request got return failed.

Solution:
Skip Journal in redfish enumerate request.

Signed-off-by: Tim Lee <timlee660101@gmail.com>