redfish: extended: dump: fix "Verify Download BMC Dump" test failed
Symptom:
"Verify Download BMC Dump" test item in test_bmc_dump.robot got failed.

Root cause:
From test report that error message is
JSONDecodeError: Expecting value: line 1 column 1 (char 0).
Due to this test item using REST method "Create User Initiated Dump"
to create bmc dump and got failed. Thus, "Get The Dump Id" return unexpected value.

Solution:
According current bmcweb design, we should using Redfish method to
create bmc dump instead of using REST method.

Tested:
Run robot "Verify Download BMC Dump" of test_bmc_dump.robot

Signed-off-by: Tim Lee <timlee660101@gmail.com>